import sys

from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Obuchenie = QtWidgets.QLabel(self.centralwidget)
        self.Obuchenie.setGeometry(QtCore.QRect(20, 20, 1081, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Obuchenie.setFont(font)
        self.Obuchenie.setObjectName("Obuchenie")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 281, 519))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Aes_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Aes_label.setFont(font)
        self.Aes_label.setObjectName("Aes_label")
        self.verticalLayout_2.addWidget(self.Aes_label)
        self.Aes_teory = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Aes_teory.setFont(font)
        self.Aes_teory.setObjectName("Aes_teory")
        self.verticalLayout_2.addWidget(self.Aes_teory)
        self.Aes_teory_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Aes_teory_2.setFont(font)
        self.Aes_teory_2.setObjectName("Aes_teory_2")
        self.verticalLayout_2.addWidget(self.Aes_teory_2)
        self.Aes_zadani = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Aes_zadani.setFont(font)
        self.Aes_zadani.setObjectName("Aes_zadani")
        self.verticalLayout_2.addWidget(self.Aes_zadani)
        self.Des_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Des_label.setFont(font)
        self.Des_label.setObjectName("Des_label")
        self.verticalLayout_2.addWidget(self.Des_label)
        self.des_teory = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.des_teory.setFont(font)
        self.des_teory.setObjectName("des_teory")
        self.verticalLayout_2.addWidget(self.des_teory)
        self.des_test = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.des_test.setFont(font)
        self.des_test.setObjectName("des_test")
        self.verticalLayout_2.addWidget(self.des_test)
        self.des_zadanie = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.des_zadanie.setFont(font)
        self.des_zadanie.setObjectName("des_zadanie")
        self.verticalLayout_2.addWidget(self.des_zadanie)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 80, 571, 791))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qest1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.qest1.setFont(font)
        self.qest1.setObjectName("qest1")
        self.verticalLayout.addWidget(self.qest1)
        self.q1a1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q1a1.setFont(font)
        self.q1a1.setObjectName("q1a1")
        self.verticalLayout.addWidget(self.q1a1)
        self.q1a2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q1a2.setFont(font)
        self.q1a2.setObjectName("q1a2")
        self.verticalLayout.addWidget(self.q1a2)
        self.q1a3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q1a3.setFont(font)
        self.q1a3.setObjectName("q1a3")
        self.verticalLayout.addWidget(self.q1a3)
        self.qest2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.qest2.setFont(font)
        self.qest2.setObjectName("qest2")
        self.verticalLayout.addWidget(self.qest2)
        self.q2a1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q2a1.setFont(font)
        self.q2a1.setObjectName("q2a1")
        self.verticalLayout.addWidget(self.q2a1)
        self.q2a2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q2a2.setFont(font)
        self.q2a2.setObjectName("q2a2")
        self.verticalLayout.addWidget(self.q2a2)
        self.q2a3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q2a3.setFont(font)
        self.q2a3.setObjectName("q2a3")
        self.verticalLayout.addWidget(self.q2a3)
        self.qest3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.qest3.setFont(font)
        self.qest3.setObjectName("qest3")
        self.verticalLayout.addWidget(self.qest3)
        self.q3a1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q3a1.setFont(font)
        self.q3a1.setObjectName("q3a1")
        self.verticalLayout.addWidget(self.q3a1)
        self.q3a2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q3a2.setFont(font)
        self.q3a2.setObjectName("q3a2")
        self.verticalLayout.addWidget(self.q3a2)
        self.q3a3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q3a3.setFont(font)
        self.q3a3.setObjectName("q3a3")
        self.verticalLayout.addWidget(self.q3a3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.q4a1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q4a1.setFont(font)
        self.q4a1.setObjectName("q4a1")
        self.verticalLayout.addWidget(self.q4a1)
        self.q4a2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q4a2.setFont(font)
        self.q4a2.setObjectName("q4a2")
        self.verticalLayout.addWidget(self.q4a2)
        self.q4a3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q4a3.setFont(font)
        self.q4a3.setObjectName("q4a3")
        self.verticalLayout.addWidget(self.q4a3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(870, 80, 401, 791))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.qest5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.qest5.setFont(font)
        self.qest5.setObjectName("qest5")
        self.verticalLayout_3.addWidget(self.qest5)
        self.q5a1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q5a1.setFont(font)
        self.q5a1.setObjectName("q5a1")
        self.verticalLayout_3.addWidget(self.q5a1)
        self.q5a2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q5a2.setFont(font)
        self.q5a2.setObjectName("q5a2")
        self.verticalLayout_3.addWidget(self.q5a2)
        self.q5a3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q5a3.setFont(font)
        self.q5a3.setObjectName("q5a3")
        self.verticalLayout_3.addWidget(self.q5a3)
        self.qest6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.qest6.setFont(font)
        self.qest6.setObjectName("qest6")
        self.verticalLayout_3.addWidget(self.qest6)
        self.q6a1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q6a1.setFont(font)
        self.q6a1.setObjectName("q6a1")
        self.verticalLayout_3.addWidget(self.q6a1)
        self.q6a2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q6a2.setFont(font)
        self.q6a2.setObjectName("q6a2")
        self.verticalLayout_3.addWidget(self.q6a2)
        self.q6a3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q6a3.setFont(font)
        self.q6a3.setObjectName("q6a3")
        self.verticalLayout_3.addWidget(self.q6a3)
        self.qest7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.qest7.setFont(font)
        self.qest7.setObjectName("qest7")
        self.verticalLayout_3.addWidget(self.qest7)
        self.q7a1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q7a1.setFont(font)
        self.q7a1.setObjectName("q7a1")
        self.verticalLayout_3.addWidget(self.q7a1)
        self.q7a2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.q7a2.setFont(font)
        self.q7a2.setObjectName("q7a2")
        self.verticalLayout_3.addWidget(self.q7a2)
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_3.addWidget(self.radioButton_12)
        self.main_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.main_text.setGeometry(QtCore.QRect(300, 80, 971, 791))
        self.main_text.setObjectName("main_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Obuchenie.setText(_translate("MainWindow", "Обучение симетричным алгоритмам шифрования DES и AES"))
        self.Aes_label.setText(_translate("MainWindow", "AES"))
        self.Aes_teory.setText(_translate("MainWindow", "Теория"))
        self.Aes_teory_2.setText(_translate("MainWindow", "Тест"))
        self.Aes_zadani.setText(_translate("MainWindow", "Задания"))
        self.Des_label.setText(_translate("MainWindow", "DES"))
        self.des_teory.setText(_translate("MainWindow", "Теория"))
        self.des_test.setText(_translate("MainWindow", "Тест"))
        self.des_zadanie.setText(_translate("MainWindow", "Задания"))
        self.qest1.setText(_translate("MainWindow", "1.    DES – это"))
        self.q1a1.setText(_translate("MainWindow", "rb1"))
        self.q1a2.setText(_translate("MainWindow", "RadioButton"))
        self.q1a3.setText(_translate("MainWindow", "RadioButton"))
        self.qest2.setText(_translate("MainWindow", "Вопрос 2"))
        self.q2a1.setText(_translate("MainWindow", "RadioButton"))
        self.q2a2.setText(_translate("MainWindow", "RadioButton"))
        self.q2a3.setText(_translate("MainWindow", "RadioButton"))
        self.qest3.setText(_translate("MainWindow", "Вопрос 3"))
        self.q3a1.setText(_translate("MainWindow", "RadioButton"))
        self.q3a2.setText(_translate("MainWindow", "RadioButton"))
        self.q3a3.setText(_translate("MainWindow", "RadioButton"))
        self.label_4.setText(_translate("MainWindow", "вопрос 4"))
        self.q4a1.setText(_translate("MainWindow", "RadioButton"))
        self.q4a2.setText(_translate("MainWindow", "RadioButton"))
        self.q4a3.setText(_translate("MainWindow", "RadioButton"))
        self.qest5.setText(_translate("MainWindow", "вопрос 5"))
        self.q5a1.setText(_translate("MainWindow", "RadioButton"))
        self.q5a2.setText(_translate("MainWindow", "q5"))
        self.q5a3.setText(_translate("MainWindow", "RadioButton"))
        self.qest6.setText(_translate("MainWindow", "Вопрос 6"))
        self.q6a1.setText(_translate("MainWindow", "RadioButton"))
        self.q6a2.setText(_translate("MainWindow", "RadioButton"))
        self.q6a3.setText(_translate("MainWindow", "RadioButton"))
        self.qest7.setText(_translate("MainWindow", "Вопрос 7"))
        self.q7a1.setText(_translate("MainWindow", "RadioButton"))
        self.q7a2.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_12.setText(_translate("MainWindow", "RadioButton"))






# Наследуемся от виджета из PyQt5.QtWidgets и от класса с интерфейсом
class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        # Вызываем метод для загрузки интерфейса из класса Ui_MainWindow,
        # остальное без изменений
        self.setupUi(self)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.exit(app.exec_())