import sys

from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtWidgets import QApplication, QMainWindow

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Obuchenie = QtWidgets.QLabel(self.centralwidget)
        self.Obuchenie.setGeometry(QtCore.QRect(20, 20, 1081, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Obuchenie.setFont(font)
        self.Obuchenie.setObjectName("Obuchenie")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 281, 519))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Aes_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Aes_label.setFont(font)
        self.Aes_label.setObjectName("Aes_label")
        self.verticalLayout_2.addWidget(self.Aes_label)
        self.Aes_teory = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Aes_teory.setFont(font)
        self.Aes_teory.setObjectName("Aes_teory")
        self.verticalLayout_2.addWidget(self.Aes_teory)
        self.Aes_teory_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Aes_teory_2.setFont(font)
        self.Aes_teory_2.setObjectName("Aes_teory_2")
        self.verticalLayout_2.addWidget(self.Aes_teory_2)
        self.Aes_zadani = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Aes_zadani.setFont(font)
        self.Aes_zadani.setObjectName("Aes_zadani")
        self.verticalLayout_2.addWidget(self.Aes_zadani)
        self.Des_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Des_label.setFont(font)
        self.Des_label.setObjectName("Des_label")
        self.verticalLayout_2.addWidget(self.Des_label)
        self.des_teory = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.des_teory.setFont(font)
        self.des_teory.setObjectName("des_teory")
        self.verticalLayout_2.addWidget(self.des_teory)
        self.des_test = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.des_test.setFont(font)
        self.des_test.setObjectName("des_test")
        self.verticalLayout_2.addWidget(self.des_test)
        self.des_zadanie = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.des_zadanie.setFont(font)
        self.des_zadanie.setObjectName("des_zadanie")
        self.verticalLayout_2.addWidget(self.des_zadanie)
        self.main_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.main_text.setGeometry(QtCore.QRect(310, 80, 961, 591))
        self.main_text.setObjectName("main_text")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(310, 80, 961, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 270, 961, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.a1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.a1.setFont(font)
        self.a1.setObjectName("a1")
        self.verticalLayout.addWidget(self.a1)
        self.a2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.a2.setFont(font)
        self.a2.setObjectName("a2")
        self.verticalLayout.addWidget(self.a2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 570, 961, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(310, 630, 961, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Obuchenie.setText(_translate("MainWindow", "Обучение симетричным алгоритмам шифрования DES и AES"))
        self.Aes_label.setText(_translate("MainWindow", "AES"))
        self.Aes_teory.setText(_translate("MainWindow", "Теория"))
        self.Aes_teory_2.setText(_translate("MainWindow", "Тест"))
        self.Aes_zadani.setText(_translate("MainWindow", "Задания"))
        self.Des_label.setText(_translate("MainWindow", "DES"))
        self.des_teory.setText(_translate("MainWindow", "Теория"))
        self.des_test.setText(_translate("MainWindow", "Тест"))
        self.des_zadanie.setText(_translate("MainWindow", "Задания"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:24pt; font-weight:600;\">Вопрос: 1</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:14pt;\">o</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">   </span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:14pt; font-weight:600;\">алгоритм для симметричного шифрования, разработанный фирмой IBM и утверждённый правительством США в 1977 году как официальный стандарт (FIPS 46-3)</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> </span></p></body></html>"))
        self.a1.setText(_translate("MainWindow", "Ответ 1"))
        self.a2.setText(_translate("MainWindow", "Ответ 1"))
        self.radioButton_3.setText(_translate("MainWindow", "Ответ 1"))
        self.pushButton.setText(_translate("MainWindow", "Следующий вопрос"))


class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(1280, 720)
        self.main_text.hide()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.exit(app.exec_())